// coinActions
export const FETCH_PORTFOLIO = "FETCH_PORTFOLIO";
export const FETCH_PORTFOLIO_AVERAGE = "FETCH_PORTFOLIO_AVERAGE";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SELL_TRANSACTION = "SELL_TRANSACTION";
export const FETCH_COIN_DATA = "FETCH_COIN_DATA";
export const FETCH_COIN_PRICES = "FETCH_COIN_PRICES";

// history 
export const GET_HISTORY_ITEMS = "GET_HISTORY_ITEMS";
export const GET_HISTORY_ITEMS_DETAILS = "GET_HISTORY_ITEMS_DETAILS";

// errors
export const NO_SUCH_COIN_IN_CMC = "NO_SUCH_COIN_IN_CMC";
export const UNKNOWN_ERROR = "UNKNOWN_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FIELDS_ARE_REQUIRED = "FIELDS_ARE_REQUIRED";
export const WRONG_CREDENTIALS = "WRONG_CREDENTIALS";

// auth
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";