// coinActions
export const FETCH_PORTFOLIO = "FETCH_PORTFOLIO";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SELL_TRANSACTION = "SELL_TRANSACTION";
export const FETCH_COIN_DATA = "FETCH_COIN_DATA";
export const FETCH_COIN_PRICES = "FETCH_COIN_PRICES";